name = "zai2api"
main = "worker.js"
compatibility_date = "2026-08-01"

# deviceToken 池 (采集后 bulk put)
[[kv_namespaces]]
binding = "ZAI_TOKENS"
id = "3ab3591419784c808d547316919c973f"

[vars]
# 客户端访问鉴权 (可选; 不设默认放行, 公网慎用)
# ZAI_AUTH_KEY = "your-client-key"
